[package]
name = "rustlibp2p-bridge"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = "symbols"

[dependencies]
libp2p-mplex = "0.42"
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
slog = { version = "2", features = ["max_level_debug", "release_max_level_debug", "nested-values"] }

[dependencies.libp2p]
version = "0.54"
default-features = false
features = ["identify", "yamux", "noise", "dns", "tcp", "tokio", "plaintext", "secp256k1", "macros", "ecdsa", "metrics", "quic", "upnp", "ping", "gossipsub"]
