[package]
name = "hashsig-glue"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.9"
hashsig = { git = "https://github.com/b-wagn/hash-sig", rev = "93eabbf76665b3922da9f05777bd3f5957644e92" }
rand = "0.9.2"
rand_chacha = "0.9.0"
thiserror = "2.0.17"
bincode = { version = "2.0", features = ["serde"] }

[lib]
crate-type = ["staticlib"]
name = "hashsig_glue"
